language: java
deploy:
  provider: releases
  api_key:
    secure: ccyM/BWHLw9pZ+wDnO6GQHHzN4WnQljlVisuFQgWQo2CyjyI47Z9OQkx7R67LCv+0QqtLQOlutGBh8QdnpPRlPFZssiTVyH8nf81Gshxsq4IDU0bHlIyJlSWP1p5EbS4C27QbayDz68dgdqVo/Zb8vfFUv9xq7LAfgeOkmGfCarRB5ZinBU48OSS2cUZddewN3CFFWUa7aoKePqGXgrE2AH6qMAHFi516udfaxRAwEQcoFoAseENeuFbNhI6O03W/iIpZvDKj1b6VvB3p7lydrgJe03qHtNc16oIZBLajTZw+6JRiUKVITVSc64CBW0Jr55Np0X+7+Buj27YxB+mCZfWCEZqkxwF02eHOMTs3rx0BhZ7jDjKokAYLUjITK5Bhnj8RXGkymsK83zwSI8VO1DdqgQD0iAJra6Nxhp01EPk8JK1pRu6IF/3DcE9yXqzWKgnQLUb6c+lKa57qoHSQ89HCPl75SZQz6h9oddsiihTJbx1HH+PNBsMTW+rQchuNh4FxIdECV1sCb7zo6IVmv7U2HQN3/9mM4B7fjyFJNnDFBubCi3ZOCFjuJWg4jjJczVSXOQ9r6D/Qxqe4neHC2u7tL7UjZX6dAn5TFb7blZlNCb+VHWgrLpwsZeIb90UDFMKSk7nvnSKfySzmkORmIRllBibmWCkypNdcG5cPwk=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-semaphore-ci-plugin
